### ISSUE TITLE
Added funval to typescript-runtime-type-benchmarks

### ISSUE THREAD

**Issue by moltar** [neuledge/funval#1]
Hey @moshest,

Great take on the validator!

I added your project to the benchmarking repo: https://github.com/moltar/typescript-runtime-type-benchmarks

**Comment by moshest** [comment]
Awesome! When you will have the results?

**Comment by moltar** [comment]
Haha you are so fast! They will be there any minute. But since you already viewed it, then GitHub may cache the images for you. Make sure to view the image by browsing to the file via the file tree. Or just wait a bit. I had some failing tests that I just fixed.

**Comment by moltar** [comment]
https://github.com/moltar/typescript-runtime-type-benchmarks/blob/master/results/bar-graph-10.x.svg

**Comment by moshest** [comment]
Thanks Roman.

From a quick look, it's looks something is wrong with the measurement. The differences are too big. I will take a better look on the next few days.

**Comment by moshest** [comment]
Well I toke a second look, looks like `ts-json-validator` uses `ajv` which extremely benefit from compiler optimizations. Not sure if we can implement the same methods on Funval, but it's definitely worth trying making the `Schema` validator run faster.

I will open a long term issue for this subject and close this one for now. Thanks again!
